language: node_js
node_js:
  - 8.5.0
script:
   - "npm run test"

deploy:
  provider: heroku
  api_key:
    secure: 422421e8-78b7-4a8f-9c13-87958c039f40
  app: strv-addressbook-lebeda-j
  on:
    repo: lebedajaromir/AdressBook