language: node_js
node_js:
  - 11.0.0
branches:
  only:
    - master
cache:
  directories:
    - node_modules
services:
  - docker
env:
  global:
- NODE_ENV=test
install:
- npm install

before_script:
  - sudo service postgresql stop
  - npm run infra
  - sleep 10
  - npm run migrate:test
script:
   - "npm run test"

deploy:
  provider: heroku
  api_key:
    secure: 422421e8-78b7-4a8f-9c13-87958c039f40
  app: strv-addressbook-lebeda-j
  strategy: git
  on:
    branch:
      - master
    repo: lebedajaromir/AdressBook