language: node_js
node_js:
- 11.0.0
branches:
  only:
  - master
cache:
  directories:
  - node_modules
services:
- docker
env:
  global:
  - NODE_ENV=test
install:
- npm install
before_script:
- sudo service postgresql stop
- npm run infra
- sleep 10
- npm run migrate:test
script:
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: VUCsQD6+TfCPqQxLObb6r5lzQQ1Ki2yKDGL1RysKVkDNspKEVs5HyspcYNBWxLYuH8z7P+smnWV0vbQDpaNFhesR5W13GLa4ubQcW4fSP1XYx1Qm5heG1i1zp3dDRz5uCvDrkA67DJmr3LzbgKskBGpWy/nzuMBefoAH5XfmqN5MxdVPsxv6QnqKTI0ZC/+p6KzAY0trNx1TkInp2hGUnreUQRe48LcowBkihP8AN5jajosjFgWlkdAxcKxc1j0kbArVf3/+27KyUw97CHBcnrqqTtZHJka1k2eCRr7cjqMRqbG2F61cKnY5Wfpn6GQPLNVoiS4tk8sZlQtPf+M//JAQRv7oJa+Nzkxc85vfvaERC3FlUFiSXUc79CP/qYdjNtaDlVtHD5wI19h0duB7/x/DR2kNSy8gE+sPoIv+6eKkdJuaHiaITHdw6R2n6m7ycDQSOZ8eY+Zizz3stNEeeTeDi+TFW6qYorBHWXx9fJy6PMUm02SEwDey/n/JJluW83MZAC0vEDRyqQxvksbkiVWHFKJva79Cf5wpQ7cZBLHaU6O8Xb5UytBX6tokF/e5s9sUfXxcJGm2XVwcLe+yj50r+E/h//eB99VvJAqI9V8iP49qla2SbwxD50f5ozd/tcwNCI75/gCheuQl0hHT81BUVj20dotmP1OXKpXqZ8s=
  app: strv-addressbook-lebeda-j
  strategy: git
  on:
    branch:
    - master
    repo: lebedajaromir/AddressBook
