version: '3'
services:
  database:
    image: sameersbn/postgresql:latest
    container_name: addressbook-users-db
    environment:
      - DB_NAME=addressbook-users,addressbook-users-test
      - PG_TRUST_LOCALNET=true
    ports:
     - "5432:5432"
#  server:
#    build: .
#    container_name: addressbook
#    depends_on: 
#      - database
#    environment:
#      - DB_SERVER="addressbook-users-db"
#      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}"
#      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}"
#      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}"  
#    ports:
#      - 3000:3000
